# Generated by Django 5.2.16 on 2026-09-23 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='이름')),
                ('order', models.IntegerField(default=0, verbose_name='차례')),
            ],
            options={
                'verbose_name': '레이어군',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PointSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='이름')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='올린 파일')),
                ('color', models.CharField(default='#e4572e', max_length=7, verbose_name='색')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='올린 때')),
                ('visible', models.BooleanField(default=True, verbose_name='지도에 보인다')),
            ],
            options={
                'verbose_name': '점묶음',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='레이어명')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('abstract', models.TextField(blank=True, verbose_name='설명')),
                ('bbox_west', models.FloatField(blank=True, null=True)),
                ('bbox_south', models.FloatField(blank=True, null=True)),
                ('bbox_east', models.FloatField(blank=True, null=True)),
                ('bbox_north', models.FloatField(blank=True, null=True)),
                ('queryable', models.BooleanField(default=True, verbose_name='클릭해 속성을 읽을 수 있다')),
                ('enabled', models.BooleanField(default=True, verbose_name='레이어 패널에 보인다')),
                ('order', models.IntegerField(default=0, verbose_name='차례')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='확인한 때')),
                ('verify_note', models.CharField(blank=True, max_length=200, verbose_name='확인 기록')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='viewer.layergroup', verbose_name='레이어군')),
            ],
            options={
                'verbose_name': '레이어',
                'ordering': ['group__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='이름표')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lon', models.FloatField(verbose_name='경도')),
                ('props', models.JSONField(blank=True, default=dict, verbose_name='딸린 속성')),
                ('pointset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='viewer.pointset', verbose_name='점묶음')),
            ],
            options={
                'verbose_name': '점',
                'ordering': ['id'],
            },
        ),
    ]
