# Generated by Django 5.2.16 on 2026-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='날짜')),
                ('upstream', models.CharField(max_length=20, verbose_name='상류')),
                ('ok', models.PositiveIntegerField(default=0, verbose_name='성공')),
                ('fail', models.PositiveIntegerField(default=0, verbose_name='실패')),
                ('blocked', models.PositiveIntegerField(default=0, verbose_name='차단 조짐')),
            ],
            options={
                'ordering': ['-day', 'upstream'],
                'constraints': [models.UniqueConstraint(fields=('day', 'upstream'), name='upstream_day_once')],
            },
        ),
    ]
