# Generated by Django 5.2.16 on 2026-09-27 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_upstream_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('line', '선'), ('polygon', '면')], max_length=10, verbose_name='갈래')),
                ('geometry', models.JSONField(verbose_name='기하 (GeoJSON)')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='이름표')),
                ('lat', models.FloatField(verbose_name='가운데 위도')),
                ('lon', models.FloatField(verbose_name='가운데 경도')),
                ('props', models.JSONField(blank=True, default=dict, verbose_name='딸린 속성')),
                ('pointset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='viewer.pointset', verbose_name='점묶음')),
            ],
            options={
                'verbose_name': '모양',
                'ordering': ['id'],
            },
        ),
    ]
