# Generated by Django 5.2.16 on 2026-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSetDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='이름')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='색')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='올린 파일')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='올린 때')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='지운 때')),
                ('client', models.CharField(blank=True, max_length=64, verbose_name='지운 곳 (접속 주소)')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='점')),
                ('lines', models.PositiveIntegerField(default=0, verbose_name='선')),
                ('polygons', models.PositiveIntegerField(default=0, verbose_name='면')),
                ('snapshot', models.JSONField(default=dict, verbose_name='사본 (GeoJSON)')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='되살린 때')),
            ],
            options={
                'verbose_name': '지운 점묶음',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
