# Generated by Django 5.2.16 on 2026-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_pointset_deletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layergroup',
            options={'ordering': ['region', 'order', 'name'], 'verbose_name': '레이어군'},
        ),
        migrations.AddField(
            model_name='layer',
            name='upstream',
            field=models.CharField(default='kigam', max_length=20, verbose_name='상류'),
        ),
        migrations.AddField(
            model_name='layergroup',
            name='region',
            field=models.CharField(choices=[('korea', '한국'), ('greenland', '그린란드'), ('antarctica', '남극')], default='korea', max_length=20, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='name',
            field=models.CharField(max_length=60, verbose_name='이름'),
        ),
        migrations.AddConstraint(
            model_name='layergroup',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='layergroup_name_per_region'),
        ),
    ]
