# Generated by Django 5.2.16 on 2026-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='kind',
            field=models.CharField(choices=[('wms', '타일'), ('vector', '벡터')], default='wms', max_length=10, verbose_name='그리는 법'),
        ),
    ]
