# Generated by Django 5.2.16 on 2026-09-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_region_china'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='elev',
            field=models.FloatField(blank=True, null=True, verbose_name='표고 (m)'),
        ),
        migrations.AddField(
            model_name='point',
            name='elev_datum',
            field=models.CharField(blank=True, max_length=20, verbose_name='높이 기준'),
        ),
        migrations.AddField(
            model_name='point',
            name='elev_source',
            field=models.CharField(blank=True, max_length=40, verbose_name='표고 출처'),
        ),
    ]
