# Generated by Django 5.2.16 on 2026-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_point_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointset',
            name='body',
            field=models.CharField(choices=[('earth', '지구'), ('moon', '달')], db_index=True, default='earth', max_length=10, verbose_name='몸'),
        ),
        migrations.AddField(
            model_name='pointsetdeletion',
            name='body',
            field=models.CharField(choices=[('earth', '지구'), ('moon', '달')], default='earth', max_length=10, verbose_name='몸'),
        ),
    ]
