# Generated by Django 5.2.16 on 2026-09-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_pointset_body_mars'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='place',
            field=models.JSONField(blank=True, default=dict, verbose_name='둘레 (VWorld)'),
        ),
    ]
