# Generated by Django 5.2.16 on 2026-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_region_uk_france'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroup',
            name='region',
            field=models.CharField(choices=[('korea', '한국'), ('greenland', '그린란드'), ('antarctica', '남극'), ('jan_mayen', '얀마옌'), ('svalbard', '스발바르'), ('japan', '일본'), ('china', '중국'), ('taiwan', '대만'), ('arctic_ocean', '북극해'), ('fennoscandia', '노르웨이·핀란드'), ('uk', '영국'), ('france', '프랑스'), ('germany', '독일'), ('spain', '스페인'), ('ireland', '아일랜드')], default='korea', max_length=20, verbose_name='지역'),
        ),
    ]
