# Generated by Django 5.2.16 on 2026-10-04 06:17

from django.db import migrations, models


def south_america_to_colombia(apps, schema_editor):
    """남미 탭(wetherilli 188)의 레이어군을 나라 탭으로 — SGB 레이어가 든 것은 브라질, 나머지(SGC)는 콜롬비아.
    묶음 "남미" 는 DB 에 없다 (wetherilli 191). 되돌렸다 다시 올 때 브라질 것이 콜롬비아로 가지 않게 상류로 가른다"""
    groups = apps.get_model("viewer", "LayerGroup").objects.filter(region="south_america")
    groups.filter(layers__upstream="sgb").distinct().update(region="brazil")
    groups.filter(region="south_america").update(region="colombia")


def colombia_to_south_america(apps, schema_editor):
    apps.get_model("viewer", "LayerGroup").objects.filter(region__in=("colombia", "brazil")).update(region="south_america")


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_region_south_america'),
    ]

    operations = [
        migrations.RunPython(south_america_to_colombia, colombia_to_south_america),
        migrations.AlterField(
            model_name='layergroup',
            name='region',
            field=models.CharField(choices=[('korea', '한국'), ('greenland', '그린란드'), ('antarctica', '남극'), ('jan_mayen', '얀마옌'), ('svalbard', '스발바르'), ('japan', '일본'), ('china', '중국'), ('taiwan', '대만'), ('arctic_ocean', '북극해'), ('fennoscandia', '노르웨이·핀란드'), ('uk', '영국'), ('france', '프랑스'), ('germany', '독일'), ('spain', '스페인'), ('ireland', '아일랜드'), ('colombia', '콜롬비아'), ('brazil', '브라질')], default='korea', max_length=20, verbose_name='지역'),
        ),
    ]
