# Generated by Django 5.2.16 on 2026-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0038_region_southeast_asia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroup',
            name='region',
            field=models.CharField(choices=[('korea', '한국'), ('greenland', '그린란드'), ('antarctica', '남극'), ('jan_mayen', '얀마옌'), ('svalbard', '스발바르'), ('japan', '일본'), ('china', '중국'), ('taiwan', '대만'), ('arctic_ocean', '북극해'), ('fennoscandia', '노르웨이·핀란드'), ('uk', '영국'), ('france', '프랑스'), ('germany', '독일'), ('spain', '스페인'), ('ireland', '아일랜드'), ('colombia', '콜롬비아'), ('brazil', '브라질'), ('peru', '페루'), ('argentina', '아르헨티나'), ('uruguay', '우루과이'), ('ecuador', '에콰도르'), ('usa', '미국'), ('mexico', '멕시코'), ('africa', '아프리카'), ('canada', '캐나다'), ('australia', '호주'), ('italy', '이탈리아'), ('portugal', '포르투갈'), ('switzerland', '스위스'), ('iceland', '아이슬란드'), ('new_zealand', '뉴질랜드'), ('mongolia', '몽골'), ('india', '인도'), ('saudi', '사우디아라비아'), ('indonesia', '인도네시아'), ('malaysia', '말레이시아'), ('philippines', '필리핀'), ('thailand', '태국'), ('austria', '오스트리아'), ('poland', '폴란드'), ('netherlands', '네덜란드'), ('belgium', '벨기에')], default='korea', max_length=20, verbose_name='지역'),
        ),
    ]
