# Generated by Django 5.2.16 on 2026-10-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0044_region_overseas'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamday',
            name='seconds',
            field=models.FloatField(default=0.0, verbose_name='걸린 시간 합(초)'),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t0',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t5',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t6',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t7',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t8',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='t9',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upstreamday',
            name='timed',
            field=models.PositiveIntegerField(default=0, verbose_name='잰 건수'),
        ),
    ]
