# Generated by Django 5.2.16 on 2026-10-07 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0047_upstream_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRunMark',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='id')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='차례')),
                ('name_ko', models.CharField(max_length=200, verbose_name='이름')),
                ('name_en', models.CharField(max_length=200, verbose_name='영어 이름')),
                ('org', models.CharField(blank=True, default='', max_length=300, verbose_name='기관')),
                ('kind', models.CharField(choices=[('fetch', 'fetch'), ('build', 'build'), ('file', 'file'), ('once', 'once')], max_length=16, verbose_name='갈래')),
                ('runs_on', models.CharField(choices=[('container', 'container'), ('host', 'host'), ('person', 'person')], max_length=16, verbose_name='돌리는 곳')),
                ('schedule', models.CharField(choices=[('hourly', 'hourly'), ('weekly', 'weekly'), ('monthly-first-monday', 'monthly-first-monday'), ('manual', 'manual'), ('once', 'once')], max_length=32, verbose_name='주기')),
                ('license', models.CharField(max_length=500, verbose_name='조건')),
                ('flags', models.JSONField(blank=True, default=list, verbose_name='표시')),
                ('commands', models.JSONField(blank=True, default=list, verbose_name='명령')),
                ('outputs', models.JSONField(blank=True, default=list, verbose_name='산출물')),
                ('raw', models.CharField(blank=True, default='', max_length=300, verbose_name='원본 자리')),
                ('docs', models.JSONField(blank=True, default=list, verbose_name='근거')),
                ('note', models.TextField(blank=True, default='', verbose_name='메모')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='고친 때')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='고친 사람')),
            ],
            options={
                'verbose_name': '데이터소스',
                'verbose_name_plural': '데이터소스',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=64, verbose_name='데이터소스')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='때')),
                ('origin', models.CharField(choices=[('admin', 'admin'), ('tab', '관리 화면'), ('seed', '씨앗'), ('import', '파일에서 옮김')], max_length=16, verbose_name='어디서')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='앞')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='뒤')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='누가')),
            ],
            options={
                'verbose_name': '데이터소스 명세의 이력',
                'verbose_name_plural': '데이터소스 명세의 이력',
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64, verbose_name='데이터소스')),
                ('command', models.CharField(blank=True, default='', max_length=100, verbose_name='명령')),
                ('started_at', models.DateTimeField(verbose_name='시작한 때')),
                ('seconds', models.FloatField(blank=True, null=True, verbose_name='걸린 초')),
                ('result', models.CharField(max_length=8, verbose_name='결과')),
                ('note', models.TextField(blank=True, default='', verbose_name='마지막 말')),
                ('upstream_version', models.CharField(blank=True, default='', max_length=300, verbose_name='상류 판')),
                ('expected', models.IntegerField(blank=True, null=True, verbose_name='센 수')),
                ('rows', models.IntegerField(blank=True, null=True, verbose_name='받은 수')),
                ('changed', models.IntegerField(blank=True, null=True, verbose_name='바뀐 것')),
                ('raw_path', models.CharField(blank=True, default='', max_length=500, verbose_name='원본 자리')),
                ('raw_sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='원본 sha256')),
                ('built_at', models.CharField(blank=True, default='', max_length=40, verbose_name='구운 때')),
                ('built_by', models.CharField(blank=True, default='', max_length=200, verbose_name='구운 것')),
                ('estimated', models.BooleanField(default=False, verbose_name='어림')),
                ('origin', models.CharField(default='container', max_length=16, verbose_name='어디서')),
            ],
            options={
                'verbose_name': '받은 차례',
                'verbose_name_plural': '받은 차례',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['source', 'started_at'], name='fetch_run_source')],
                'constraints': [models.UniqueConstraint(fields=('source', 'started_at', 'origin'), name='fetch_run_once')],
            },
        ),
    ]
