# Generated by Django 5.2.16 on 2026-10-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0048_data_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcechange',
            name='by_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='누가(이름)'),
        ),
    ]
